export {};

const APP_NAME_UPPERCASE = 'HOMECHEF';

export const STORAGE_KEYS = {
    AUTH_GOOGLE: `${APP_NAME_UPPERCASE}_GOOGLE_AUTH_TOKEN`,
    AUTH_FACEBOOK: `${APP_NAME_UPPERCASE}_FACEBOOK_AUTH_TOKEN`,
    AUTHENTICATED_WITH: `${APP_NAME_UPPERCASE}_AUTHENTICATED_WITH`,
};
